version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: barbercore_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-barbercore}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-barbercore_secret}
      POSTGRES_DB: ${POSTGRES_DB:-barbercore_db}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-rls.sql:/docker-entrypoint-initdb.d/01-rls.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER:-barbercore}']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: barbercore_redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD:-redis_secret} --appendonly yes
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', '--no-auth-warning', '-a', '${REDIS_PASSWORD:-redis_secret}', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ../../apps/api
      dockerfile: ../../infra/docker/api.Dockerfile
    container_name: barbercore_api
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      DATABASE_URL: postgresql://${POSTGRES_USER:-barbercore}:${POSTGRES_PASSWORD:-barbercore_secret}@postgres:5432/${POSTGRES_DB:-barbercore_db}?schema=public
      REDIS_URL: redis://:${REDIS_PASSWORD:-redis_secret}@redis:6379
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET:-change_me_access_secret}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET:-change_me_refresh_secret}
      JWT_ACCESS_EXPIRES_IN: ${JWT_ACCESS_EXPIRES_IN:-15m}
      JWT_REFRESH_EXPIRES_IN: ${JWT_REFRESH_EXPIRES_IN:-30d}
      KAVENEGAR_API_KEY: ${KAVENEGAR_API_KEY:-}
      ZARINPAL_MERCHANT_ID: ${ZARINPAL_MERCHANT_ID:-}
      ARVAN_ACCESS_KEY: ${ARVAN_ACCESS_KEY:-}
      ARVAN_SECRET_KEY: ${ARVAN_SECRET_KEY:-}
      ARVAN_BUCKET_NAME: ${ARVAN_BUCKET_NAME:-barbercore}
      ARVAN_ENDPOINT: ${ARVAN_ENDPOINT:-https://s3.ir-thr-at1.arvanstorage.ir}
      APP_URL: ${APP_URL:-http://localhost:3000}
      API_PORT: ${API_PORT:-4000}
    ports:
      - '4000:4000'
    profiles:
      - full

  web:
    build:
      context: ../../apps/web
      dockerfile: ../../infra/docker/web.Dockerfile
    container_name: barbercore_web
    restart: unless-stopped
    depends_on:
      - api
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:4000/api/v1}
      NEXT_PUBLIC_APP_URL: ${APP_URL:-http://localhost:3000}
    ports:
      - '3000:3000'
    profiles:
      - full

volumes:
  postgres_data:
  redis_data:

networks:
  default:
    name: barbercore_network
